# Generated by Django 4.1 on 2022-08-07 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('snack', models.CharField(choices=[('B', 'Beer'), ('S', 'Soda'), ('H', 'Hot Dog'), ('N', 'Nachos')], default='B', max_length=1)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.stadium')),
            ],
        ),
    ]
